name: generate github profile metrics

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-metrics
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer: ${{ github.repository_owner }}
          base: ""
          output_branches: main
          filename: output/github-metrics.svg
          base_indent: 0
          config_timezone: Asia/Tokyo
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_languages: yes
          plugin_languages_ignored: html,css,scss,sass,less
          plugin_languages_other: yes
          plugin_contributors: yes
          plugin_contributors_sort: commits
          plugin_notable: yes
          plugin_issues: yes
          plugin_issues_limit: 3
          plugin_issues_delay: 0.5
          plugin_pull_requests: yes
          plugin_pull_requests_limit: 3
          plugin_pull_requests_delay: 0.5
          plugin_stargazers: yes
          plugin_stargazers_limit: 3
          plugin_stargazers_delay: 0.5
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_delay: 0.5
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics_limit: 10
          plugin_topics_mode: icons
          plugin_followup: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_repositories: no
          plugin_repositories_starred: no
          plugin_discussions: yes
          plugin_discussions_limit: 3
          plugin_discussions_delay: 0.5
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A .
          git commit -m "generated github profile metrics" || exit 0
          git push

