name: generate github profile metrics

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-metrics
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer: ${{ github.repository_owner }}
          output_branches: main
          filename: output/github-metrics.svg
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_ignored: html,css,scss,sass,less
          plugin_languages_other: yes
