name: generate github profile metrics

on:
  # run automatically every 24 hours
  schedule:
    - cron: '0 0 * * *'

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-metrics
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer: ${{ github.repository_owner }}
          output_branches: main
          filename: output/github-metrics.svg
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_ignored: html,css,scss,sass,less
          plugin_languages_other: yes
